# ===========================================
# 1C Configuration Build Script
# Проект: andreymatanin-project
# ===========================================

param(
    [string]$ConfigName = "andreym",
    [string]$OutputDir = "artifacts/build",
    [string]$RepositoryPath = $env:V8_REPOSITORY_PATH
)

Write-Host "=== 1C Build Script ===" -ForegroundColor Cyan
Write-Host "Configuration: $ConfigName" -ForegroundColor Yellow
Write-Host "Output: $OutputDir" -ForegroundColor Magenta
Write-Host "Repository: $RepositoryPath" -ForegroundColor Green
Write-Host "=========================" -ForegroundColor Cyan

# Создаем выходную директорию
New-Item -ItemType Directory -Path $OutputDir -Force | Out-Null

# Проверяем доступность 1С (симуляция)
Write-Host "Checking 1C availability..." -ForegroundColor Gray
$1cPath = "C:\Program Files\1C\1CEStart\bin\designer.exe"
if (Test-Path $1cPath) {
    Write-Host "✓ 1C Designer found at: $1cPath" -ForegroundColor Green
} else {
    Write-Host "⚠ 1C Designer not found (simulation mode)" -ForegroundColor Yellow
}

# Симуляция получения конфигурации из хранилища
Write-Host "Getting configuration from repository..." -ForegroundColor Gray
Start-Sleep -Seconds 2
Write-Host "✓ Configuration loaded from repository" -ForegroundColor Green

# Создаем CF файл
$cfFile = Join-Path $OutputDir "$ConfigName.cf"
Write-Host "Creating CF file: $cfFile" -ForegroundColor Gray

@"
# ===========================================
# 1C Configuration File
# Generated by: GitHub Actions CI/CD
# Project: andreymatanin-project
# ===========================================

Configuration: $ConfigName
Version: 1.0.$(Get-Date -Format "yyyyMMdd.HHmm")
Build Date: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
Repository: $RepositoryPath
Git Commit: $(git rev-parse --short HEAD 2>$null || echo "N/A")
Git Branch: $(git branch --show-current 2>$null || echo "N/A")

# Metadata
Platform: 1C:Enterprise 8.3
ConfigurationType: Main
Compatibility: 8.3.20

# Modules
- MainModule
- CommonModules
- Reports
- DataProcessors

# Dependencies
- StandardSubsystems (version: 2.5)
- CommonForms (version: 1.3)

# Build Information
BuildMachine: $env:COMPUTERNAME
BuildUser: $env:USERNAME
BuildSystem: GitHub Actions
"@ | Out-File -FilePath $cfFile -Encoding UTF8

# Создаем backup
$backupDir = "artifacts/backups"
New-Item -ItemType Directory -Path $backupDir -Force | Out-Null
$backupFile = Join-Path $backupDir "$ConfigName-$(Get-Date -Format 'yyyyMMdd-HHmmss').cf"
Copy-Item $cfFile $backupFile -Force

Write-Host "✓ Build completed successfully!" -ForegroundColor Green
Write-Host "✓ CF file created: $cfFile" -ForegroundColor Green
Write-Host "✓ Backup created: $backupFile" -ForegroundColor Green

# Статистика
$fileInfo = Get-Item $cfFile
Write-Host "`n=== Build Statistics ===" -ForegroundColor Cyan
Write-Host "File size: $([math]::Round($fileInfo.Length/1KB, 2)) KB" -ForegroundColor White
Write-Host "Created: $($fileInfo.CreationTime)" -ForegroundColor White
Write-Host "Modified: $($fileInfo.LastWriteTime)" -ForegroundColor White

return $cfFile

# Возвращаем путь к созданному файлу (добавьте в конец скрипта)
$cfFile = Join-Path $OutputDir "$ConfigName.cf"
if (Test-Path $cfFile) {
    Write-Host "Build output: $cfFile" -ForegroundColor Green
    # Записываем путь в переменную для GitHub Actions
    echo "CF_FILE_PATH=$cfFile" >> $env:GITHUB_ENV
    echo "CF_FILE_NAME=$ConfigName.cf" >> $env:GITHUB_ENV
} else {
    Write-Error "CF file was not created"
    exit 1
}
